# Generated by Django 3.2.3 on 2021-06-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidersAndCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('cliente', 'cliente'), ('proveedor', 'proveedor')], default='cliente', max_length=10, verbose_name='¿Proveedor o Cliente?')),
                ('names_full', models.CharField(max_length=50, verbose_name='Nombres y apellidos')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='Email')),
                ('status', models.CharField(choices=[('inactivo', 'inactivo'), ('activo', 'activo')], default='activo', max_length=10, verbose_name='Estado')),
                ('direction', models.TextField(blank=True, max_length=255, verbose_name='Direción')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'db_table': 'providers_and_custormers',
            },
        ),
    ]
