# Generated by Django 3.2.3 on 2021-06-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers_and_customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersandcustomers',
            name='direction',
            field=models.TextField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
    ]
