# Generated by Django 3.2.3 on 2021-06-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(max_length=255, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='product.product', verbose_name='Producto')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
