# Generated by Django 3.2.3 on 2021-06-11 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers_and_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dozens_list', models.CharField(max_length=250, verbose_name='Lista de docenas por id')),
                ('number_of_dozens', models.IntegerField(verbose_name='Cantidad')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total precio')),
                ('money_paid', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Dinero pagado')),
                ('total_money_owed', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Dinero total adeudado')),
                ('status', models.CharField(choices=[('al contado', 'al contado'), ('giro', 'giro'), ('deposito', 'deposito')], default='al contado', max_length=30, verbose_name='Estado')),
                ('note', models.TextField(max_length=250, null=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='providers_and_customers.providersandcustomers', verbose_name='Clientes')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
