# Generated by Django 3.2.3 on 2021-07-03 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sizes', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Nombre del modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='category.category', verbose_name='Categoria')),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='SizesAndModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Précio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.model', verbose_name='Modelo')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sizes.sizes', verbose_name='Talla')),
            ],
            options={
                'db_table': 'models_sizes',
            },
        ),
        migrations.AddField(
            model_name='model',
            name='sizes',
            field=models.ManyToManyField(through='model.SizesAndModels', to='sizes.Sizes', verbose_name='Tallas'),
        ),
    ]
