# Generated by Django 3.2.3 on 2021-06-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del modelo', max_length=30, unique=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('category', models.ForeignKey(help_text='Seleccione la categoria a la que pertenecerá este modelo', on_delete=django.db.models.deletion.PROTECT, related_name='models', to='category.category', verbose_name='Categoria')),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='SizesAndModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de este talla', max_digits=5, verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.model')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sizes.sizes')),
            ],
            options={
                'db_table': 'sizes_and_models_pivot',
            },
        ),
        migrations.AddField(
            model_name='model',
            name='sizes',
            field=models.ManyToManyField(help_text='¿Que tallas va  a tener este modelo?', through='model.SizesAndModels', to='sizes.Sizes', verbose_name='Tallas'),
        ),
    ]
