# Generated by Django 3.2.3 on 2021-06-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0001_initial'),
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='sizes',
        ),
        migrations.CreateModel(
            name='SizesAndModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de este talla', max_digits=5, verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='model.model')),
                ('size_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sizes.sizes')),
            ],
            options={
                'db_table': 'sizes_and_models_pivot',
            },
        ),
        migrations.AddField(
            model_name='model',
            name='sizes',
            field=models.ManyToManyField(help_text='¿Que tallas va  a tener este modelo?', through='model.SizesAndModels', to='sizes.Sizes', verbose_name='Tallas'),
        ),
    ]
