# Generated by Django 3.2.3 on 2021-06-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20210612_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizesandmodels',
            old_name='model_id',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='sizesandmodels',
            old_name='size_id',
            new_name='size',
        ),
    ]
