# Generated by Django 3.2.3 on 2021-06-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20210612_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='category',
        ),
        migrations.RemoveField(
            model_name='model',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='model',
            name='name',
        ),
        migrations.RemoveField(
            model_name='model',
            name='price',
        ),
        migrations.RemoveField(
            model_name='model',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='model',
            name='update_at',
        ),
        migrations.AlterModelTable(
            name='model',
            table=None,
        ),
    ]
