# Generated by Django 3.2.3 on 2021-06-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20210612_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='price',
        ),
    ]
