# Generated by Django 3.2.3 on 2021-06-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('color', models.CharField(max_length=250, null=True, verbose_name='Color')),
                ('type', models.CharField(max_length=250, verbose_name='Tipo de material')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tipo de material')),
                ('note', models.TextField(max_length=255, null=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material', to='materials.material', verbose_name='Inventario')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
