# Generated by Django 3.2.3 on 2021-06-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('providers_and_customers', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='providers_and_customers.providersandcustomers', verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Existencias'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='color',
            field=models.CharField(blank=True, choices=[('negro', 'negro'), ('plomo', 'plomo'), ('cafe', 'cafe'), ('amarillo', 'amarillo'), ('verde', 'verde'), ('blanco', 'rojo'), ('azul', 'azul'), ('rojo', 'rojo')], max_length=30, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.material', verbose_name='Material'),
        ),
    ]
