# Generated by Django 3.2.3 on 2021-06-25 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers_and_customers', '0001_initial'),
        ('inventory', '0003_auto_20210624_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='providers_and_customers.providersandcustomers', verbose_name='Proveedor'),
        ),
    ]
