# Generated by Django 3.2.3 on 2021-06-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0001_initial'),
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dozen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('material', models.CharField(choices=[('cuero', 'cuero'), ('gamusa', 'gamusa')], default='cuero', max_length=30, verbose_name='Material')),
                ('status', models.CharField(choices=[('disponible', 'disponible'), ('vendido', 'vendido')], default='disponible', max_length=30, verbose_name='Estado')),
                ('note', models.TextField(max_length=30, null=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='model.model', verbose_name='Modelo')),
                ('sizes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='sizes.sizes', verbose_name='Talla')),
            ],
            options={
                'db_table': 'dozens',
            },
        ),
    ]
