# Generated by Django 3.2.3 on 2021-07-03 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dozen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('cuero', 'cuero'), ('gamusa', 'gamusa')], default='cuero', max_length=30, verbose_name='Material')),
                ('color', models.CharField(choices=[('negro', 'negro'), ('plomo', 'plomo'), ('cafe', 'cafe'), ('amarillo', 'amarillo'), ('verde', 'verde'), ('blanco', 'rojo'), ('azul', 'azul'), ('rojo', 'rojo')], max_length=30, verbose_name='Color')),
                ('status', models.CharField(choices=[('disponible', 'disponible (1)'), ('aparado_en_produccion', 'Aparado en producción (2)'), ('aparado_finalizado', 'Aparado finalizado (3)'), ('armado_en_produccion', 'Armado en producción (4)'), ('armado_finalizado', 'Armado finalizado (5)'), ('produccion_finalizada', 'Produccion finalizada (6)'), ('vendido', 'Docena Vendida')], default='disponible', max_length=30, verbose_name='Estado actual de la docena')),
                ('note', models.TextField(blank=True, max_length=250, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'db_table': 'dozens',
            },
        ),
        migrations.CreateModel(
            name='DozensOfAparadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('produccion', 'aparado en producción'), ('finalizado', 'aparado finalizado')], max_length=30, verbose_name='Estado')),
                ('note', models.TextField(blank=True, max_length=250, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'db_table': 'dozens_of_aparadores',
            },
        ),
        migrations.CreateModel(
            name='DozensOfArmadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('produccion', 'armado en produccion'), ('finalizado', 'armado finalizado')], max_length=30, verbose_name='Estado')),
                ('note', models.TextField(blank=True, max_length=250, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'db_table': 'dozens_of_armadores',
            },
        ),
        migrations.CreateModel(
            name='DozensOfCortadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=250, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'db_table': 'dozens_of_cortadores',
            },
        ),
        migrations.CreateModel(
            name='DozensOfRematadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=250, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('dozen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rematador', to='dozens.dozen', verbose_name='Docena')),
            ],
            options={
                'db_table': 'dozens_of_rematadores',
            },
        ),
    ]
