# Generated by Django 3.2.3 on 2021-06-22 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sizes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dozen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('cuero', 'cuero'), ('gamusa', 'gamusa')], default='cuero', max_length=30, verbose_name='Material')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('status', models.CharField(choices=[('disponible', 'disponible (1)'), ('aparado_en_produccion', 'Aparado en producción (2)'), ('aparado_finalizado', 'Aparado finalizado (3)'), ('armado_en_produccion', 'Armado en producción (4)'), ('armado_finalizado', 'Armado finalizado (5)'), ('produccion_finalizada', 'Produccion finalizada (6)'), ('vendido', 'Docena Vendida')], default='disponible', max_length=30, verbose_name='Estado')),
                ('note', models.TextField(blank=True, max_length=250, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dozens', to='model.model', verbose_name='Modelo')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dozens', to='sizes.sizes', verbose_name='Talla')),
            ],
            options={
                'db_table': 'dozens',
            },
        ),
        migrations.CreateModel(
            name='DozensOfRematadoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=250, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('dozen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rematador', to='dozens.dozen', verbose_name='Docena')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rematadoras', to=settings.AUTH_USER_MODEL, verbose_name='Rematadoras')),
            ],
            options={
                'db_table': 'dozens_of_rematadoras',
            },
        ),
        migrations.CreateModel(
            name='DozensOfCortadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=250, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('dozen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cortador', to='dozens.dozen', verbose_name='Docena')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortadores', to=settings.AUTH_USER_MODEL, verbose_name='Cortadores')),
            ],
            options={
                'db_table': 'dozens_of_cortadores',
            },
        ),
        migrations.CreateModel(
            name='DozensOfArmadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('produccion', 'armado en produccion'), ('finalizado', 'armado finalizado')], max_length=30, verbose_name='Estado')),
                ('note', models.TextField(blank=True, max_length=250, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('dozen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='armador', to='dozens.dozen', verbose_name='Docena')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armadores', to=settings.AUTH_USER_MODEL, verbose_name='Armadores')),
            ],
            options={
                'db_table': 'dozens_of_armadores',
            },
        ),
        migrations.CreateModel(
            name='DozensOfAparadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('produccion', 'aparado en producción'), ('finalizado', 'aparado finalizado')], max_length=30, verbose_name='Estado')),
                ('note', models.TextField(blank=True, max_length=250, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('dozen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aparador', to='dozens.dozen', verbose_name='Docena')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aparadores', to=settings.AUTH_USER_MODEL, verbose_name='Aparadores')),
            ],
            options={
                'db_table': 'dozens_of_aparadores',
            },
        ),
    ]
