# Generated by Django 3.2.3 on 2021-06-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dozens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dozen',
            name='code',
            field=models.CharField(default=None, max_length=9, verbose_name='Codigo'),
            preserve_default=False,
        ),
    ]
