# Generated by Django 3.2.3 on 2021-06-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dozens', '0002_dozen_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dozen',
            name='code',
            field=models.CharField(max_length=9, unique=True, verbose_name='Codigo'),
        ),
    ]
