# Generated by Django 3.2.3 on 2021-06-25 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dozens', '0003_alter_dozen_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dozen',
            name='code',
        ),
    ]
