# Generated by Django 3.2.3 on 2021-06-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dozens', '0004_remove_dozen_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dozen',
            name='color',
            field=models.CharField(choices=[('negro', 'negro'), ('plomo', 'plomo'), ('cafe', 'cafe'), ('amarillo', 'amarillo'), ('verde', 'verde'), ('blanco', 'rojo'), ('azul', 'azul'), ('rojo', 'rojo')], max_length=30, verbose_name='Color'),
        ),
    ]
