# Generated by Django 3.2.3 on 2021-06-26 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dozens', '0005_alter_dozen_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='DozensOfRematadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=250, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'db_table': 'dozens_of_rematadores',
            },
        ),
        migrations.AlterField(
            model_name='dozen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='dozen',
            name='status',
            field=models.CharField(choices=[('disponible', 'disponible (1)'), ('aparado_en_produccion', 'Aparado en producción (2)'), ('aparado_finalizado', 'Aparado finalizado (3)'), ('armado_en_produccion', 'Armado en producción (4)'), ('armado_finalizado', 'Armado finalizado (5)'), ('produccion_finalizada', 'Produccion finalizada (6)'), ('vendido', 'Docena Vendida')], default='disponible', max_length=30, verbose_name='Estado actual de la docena'),
        ),
        migrations.AlterField(
            model_name='dozen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='dozensofaparadores',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='dozensofaparadores',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='dozensofarmadores',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='dozensofarmadores',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='dozensofcortadores',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='dozensofcortadores',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.DeleteModel(
            name='DozensOfRematadoras',
        ),
        migrations.AddField(
            model_name='dozensofrematadores',
            name='dozen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rematador', to='dozens.dozen', verbose_name='Docena'),
        ),
        migrations.AddField(
            model_name='dozensofrematadores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rematadores', to=settings.AUTH_USER_MODEL, verbose_name='Rematadores'),
        ),
    ]
