# Generated by Django 3.2.3 on 2021-06-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre de la talla'),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='size',
            field=models.CharField(max_length=30, verbose_name='Talla ejemplo 38-42'),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
