# Generated by Django 3.2.3 on 2021-06-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizes',
            name='note',
        ),
        migrations.AddField(
            model_name='sizes',
            name='size',
            field=models.CharField(default=None, max_length=30, verbose_name='Talla'),
            preserve_default=False,
        ),
    ]
