# Generated by Django 3.2.3 on 2021-06-05 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(max_length=255, null=True, verbose_name='Descripción')),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('note', models.TextField(max_length=255, null=True, verbose_name='Nota')),
                ('created_at', models.DateField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='apps.product', verbose_name='Producto')),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del modelo', max_length=30, unique=True, verbose_name='Nombre')),
                ('sizes', models.CharField(help_text='¿Que tallas va  a tener este modelo?', max_length=120, verbose_name='Tallas')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de este modelo', max_digits=5, verbose_name='Precio')),
                ('category', models.ForeignKey(help_text='Seleccione la categoria a la que pertenecerá este modelo', on_delete=django.db.models.deletion.PROTECT, related_name='models', to='apps.category', verbose_name='Categoria')),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.CreateModel(
            name='Dozen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('material', models.CharField(choices=[('cuero', 'cuero'), ('gamusa', 'gamusa')], default='cuero', max_length=30, verbose_name='Material')),
                ('status', models.CharField(choices=[('disponible', 'disponible'), ('vendido', 'vendido')], default='disponible', max_length=30, verbose_name='Estado')),
                ('note', models.TextField(max_length=30, null=True, verbose_name='Nota')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Fecha de creacion')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='apps.model', verbose_name='Modelo')),
                ('sizes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sizes', to='apps.sizes', verbose_name='Talla')),
            ],
            options={
                'db_table': 'dozens',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='apps.product', verbose_name='Producto'),
        ),
    ]
