# Generated by Django 3.2.3 on 2021-06-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_inventory_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='colors',
        ),
        migrations.AddField(
            model_name='inventory',
            name='color',
            field=models.CharField(max_length=250, null=True, verbose_name='Color'),
        ),
    ]
